### ISSUE TITLE
peft版本

### ISSUE THREAD

**Issue by cxj01** [LiuHC0428/LAW-GPT#11]
peft  我装了  0.0.1 0.0.2 0.2.0 0.1.0 0.3.0  这几个版本 都没有 BottleneckConfig  
ImportError: cannot import name 'BottleneckConfig' from 'peft' (/root/anaconda3/envs/chat_glm/lib/python3.9/site-packages/peft/__init__.py)

**Comment by Sblue-G** [comment]
我最后把peft uninstall了，于是神奇般的能跑了。。。我也不知道为啥
