### ISSUE TITLE
运行demo.py报错，都按照操作配置了环境

### ISSUE THREAD

**Issue by xuanxuanzl** [LiuHC0428/LAW-GPT#17]
报错内容：
D:\AnaConda\envs\chatLei-weitiao-test\python.exe D:/project/LAW-GPT-main/src/demo.py
Traceback (most recent call last):
  File "D:\project\LAW-GPT-main\src\demo.py", line 14, in <module>
    from peft import (
ImportError: cannot import name 'get_peft_model' from 'peft' (unknown location)

Process finished with exit code 1
截图：
![图片](https://github.com/LiuHC0428/LAW-GPT/assets/104403726/e25f3e65-37a2-442a-9509-88f1fcb8aaf6)

环境：python3.10 win cuda11.8

**Comment by yaosh000** [comment]
如何解决
